
function:
  handler: src/ltl-dispatch.handler
  name: ${self:service}-ltl-dispatch-${self:provider.stage}
  description: omni fourkites ltl dispatch - ${self:provider.stage}
  memorySize: 256
  timeout: 60
  package:
    include:
    - src/ltl-dispatch.py
    - psycopg2/*
  # events:  
  #   - schedule:
  #       name: omni-dw-fourkites-ltl-dispatch-${self:provider.stage}
  #       description: 'schedule cloud watch event on fourkites ltl dispatch lambda for every 30 minutes'
  #       rate: rate(30 minutes)
  environment:
    db_username: ${ssm:/omni-dw/${self:provider.stage}/db/user}
    db_password: ${ssm:/omni-dw/${self:provider.stage}/db/password}
    db_name: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    db_host: ${ssm:/omni-dw/${self:provider.stage}/db/host}
    db_port: ${ssm:/omni-dw/${self:provider.stage}/db/port} 
    REGION: ${self:provider.region}
    fourkites_url: ${ssm:/omni-dw-fourkites/${self:provider.stage}/url}    
    fourkites_username: ${ssm:/omni-dw-fourkites/${self:provider.stage}/auth/username}
    fourkites_password: ${ssm:/omni-dw-fourkites/${self:provider.stage}/auth/password}
    fourkites_tablename: ${ssm:/omni-dw-fourkites/${self:provider.stage}/ltlDispatch/table}
    fourkites_tableindex: ${ssm:/omni-dw-fourkites/${self:provider.stage}/ltl-dispatch/fileNumber/index}